2022-11-23 13:50:50,201 ERROR frappe New Exception collected with id: 2022-11-23 13:50:49.153520-127.0.0.1-acf
Site: deepak.com
Form Dict: {'data': {'team': 'SDC', 'project': 'CMC', 'emails': ['komalpreetkaur@gndec.ac.in', 'veerpal@gndec.ac.in', 'simranjeet@gndec.ac.in']}, 'cmd': 'gameplan.api.onboarding'}
2022-11-23 15:01:54,918 ERROR frappe New Exception collected with id: 2022-11-23 15:01:54.744320-127.0.0.1-6b0
Site: deepak.com
Form Dict: {'data': {'team': 'SDC', 'project': 'CMC', 'emails': ['komalpreetkaur@gndec.ac.in', 'veerpal@gndec.ac.in', 'simranjeet@gndec.ac.in']}, 'cmd': 'gameplan.api.onboarding'}
2022-11-23 17:34:44,987 ERROR frappe New Exception collected with id: 2022-11-23 17:34:44.684495-127.0.0.1-faa
Site: deepak.com
Form Dict: {'data': {'team': 'SDC', 'project': 'CMC', 'emails': ['simranjeet@gndec.ac.in', 'veerpal@gndec.ac.in', 'komalpreetkaur@gndec.ac.in']}, 'cmd': 'gameplan.api.onboarding'}
2022-11-23 17:36:28,395 ERROR frappe New Exception collected with id: 2022-11-23 17:36:28.330892-127.0.0.1-ee5
Site: deepak.com
Form Dict: {'data': {'team': 'SDC', 'project': 'CMC', 'emails': ['simranjeet@gndec.ac.in', 'veerpal@gndec.ac.in', 'komalpreetkaur@gndec.ac.in']}, 'cmd': 'gameplan.api.onboarding'}
2022-11-23 17:37:29,021 ERROR frappe New Exception collected with id: 2022-11-23 17:37:28.900518-127.0.0.1-30d
Site: deepak.com
Form Dict: {'data': {'team': 'SDC', 'project': 'CMC', 'emails': ['veerpal@gndec.ac.in', 'simranjeet@gndec.ac.in', 'komalpreetkaur@gndec.ac.in']}, 'cmd': 'gameplan.api.onboarding'}
2022-11-23 17:52:07,037 ERROR frappe New Exception collected with id: 2022-11-23 17:52:06.819267-127.0.0.1-750
Site: deepak.com
Form Dict: {'data': {'team': 'SDC', 'project': 'CMC', 'emails': ['veerpal@gndec.ac.in', 'simranjeet@gndec.ac.in', 'komalpreetkaur@gndec.ac.in']}, 'cmd': 'gameplan.api.onboarding'}
2022-11-23 17:53:34,615 ERROR frappe New Exception collected with id: 2022-11-23 17:53:34.467272-127.0.0.1-ca9
Site: deepak.com
Form Dict: {'data': {'team': 'SDC', 'project': 'CMC', 'emails': ['veerpal@gndec.ac.in', 'simranjeet@gndec.ac.in', 'jasjitkaur@gndec.ac.in']}, 'cmd': 'gameplan.api.onboarding'}
2022-11-23 17:54:57,741 ERROR frappe New Exception collected with id: 2022-11-23 17:54:57.593331-127.0.0.1-649
Site: deepak.com
Form Dict: {'data': {'team': 'SDC', 'project': 'CMC', 'emails': ['veerpal@gndec.ac.in', 'simranjeet@gndec.ac.in', 'jasjitkaur@gndec.ac.in']}, 'cmd': 'gameplan.api.onboarding'}
2022-11-23 17:55:03,240 ERROR frappe New Exception collected with id: 2022-11-23 17:55:03.137182-127.0.0.1-f04
Site: deepak.com
Form Dict: {'data': {'team': 'SDC', 'project': 'CMC', 'emails': ['veerpal@gndec.ac.in', 'simranjeet@gndec.ac.in', 'jasjitkaur@gndec.ac.in']}, 'cmd': 'gameplan.api.onboarding'}
2022-11-23 17:55:47,111 ERROR frappe New Exception collected with id: 2022-11-23 17:55:47.001519-127.0.0.1-79b
Site: deepak.com
Form Dict: {'data': {'team': 'SDC', 'project': 'CMC', 'emails': ['veerpal@gndec.ac.in', 'simranjeet@gndec.ac.in', 'jasjitkaur@gndec.ac.in']}, 'cmd': 'gameplan.api.onboarding'}
2022-11-24 00:11:06,364 ERROR frappe New Exception collected with id: 2022-11-24 00:11:05.162543-127.0.0.1-17e
Site: deepak.com
Form Dict: {'doctype': 'Team Discussion', 'name': '1', 'cmd': 'frappe.client.get'}
2022-11-24 00:28:40,903 ERROR frappe New Exception collected with id: 2022-11-24 00:28:40.705715-127.0.0.1-1c3
Site: deepak.com
Form Dict: {'doctype': 'Team Notification', 'name': 1, 'fieldname': {'read': 1}, 'cmd': 'frappe.client.set_value'}
2022-11-24 00:47:12,704 ERROR frappe New Exception collected with id: 2022-11-24 00:47:11.355165-127.0.0.1-973
Site: deepak.com
Form Dict: {'cmd': 'frappe.desk.desktop.get_workspace_sidebar_items'}
2022-11-24 00:53:18,615 ERROR frappe New Exception collected with id: 2022-11-24 00:53:17.968003-127.0.0.1-d04
Site: deepak.com
Form Dict: {'cmd': 'frappe.desk.doctype.tag.tag.get_tags_list_for_awesomebar'}
2022-11-24 00:53:18,692 ERROR frappe New Exception collected with id: 2022-11-24 00:53:17.945483-127.0.0.1-df3
Site: deepak.com
Form Dict: {'start': '2022-11-24', 'end': '2022-11-24'}
2022-11-24 11:04:42,458 ERROR frappe Could not take error snapshot: (2003, "Can't connect to MySQL server on '127.0.0.1' ([Errno 111] Connection refused)")
Site: deepak.com
Form Dict: {}
Traceback (most recent call last):
  File "/home/spider/deepak_bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/spider/deepak_bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: -8275639797106111249

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/spider/deepak_bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 613, in connect
    sock = socket.create_connection(
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/spider/deepak_bench/apps/frappe/frappe/app.py", line 42, in application
    init_request(request)
  File "/home/spider/deepak_bench/apps/frappe/frappe/app.py", line 120, in init_request
    frappe.local.http_request = HTTPRequest()
  File "/home/spider/deepak_bench/apps/frappe/frappe/auth.py", line 36, in __init__
    self.set_session()
  File "/home/spider/deepak_bench/apps/frappe/frappe/auth.py", line 70, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/spider/deepak_bench/apps/frappe/frappe/auth.py", line 115, in __init__
    self.make_session(resume=True)
  File "/home/spider/deepak_bench/apps/frappe/frappe/auth.py", line 203, in make_session
    frappe.local.session_obj = Session(
  File "/home/spider/deepak_bench/apps/frappe/frappe/sessions.py", line 238, in __init__
    self.resume()
  File "/home/spider/deepak_bench/apps/frappe/frappe/sessions.py", line 310, in resume
    validate_ip_address(self.user)
  File "/home/spider/deepak_bench/apps/frappe/frappe/auth.py", line 407, in validate_ip_address
    frappe.get_cached_value("User", user, user_fields, as_dict=True)
  File "/home/spider/deepak_bench/apps/frappe/frappe/__init__.py", line 1141, in get_cached_value
    doc = get_cached_doc(doctype, name)
  File "/home/spider/deepak_bench/apps/frappe/frappe/__init__.py", line 1082, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/spider/deepak_bench/apps/frappe/frappe/__init__.py", line 1175, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/spider/deepak_bench/apps/frappe/frappe/model/document.py", line 72, in get_doc
    controller = get_controller(doctype)
  File "/home/spider/deepak_bench/apps/frappe/frappe/model/base_document.py", line 77, in get_controller
    return _get_controller()
  File "/home/spider/deepak_bench/apps/frappe/frappe/model/base_document.py", line 47, in _get_controller
    module_name, custom = frappe.db.get_value(
  File "/home/spider/deepak_bench/apps/frappe/frappe/database/database.py", line 456, in get_value
    result = self.get_values(
  File "/home/spider/deepak_bench/apps/frappe/frappe/database/database.py", line 553, in get_values
    out = self._get_values_from_table(
  File "/home/spider/deepak_bench/apps/frappe/frappe/database/database.py", line 769, in _get_values_from_table
    query = frappe.qb.engine.get_query(
  File "/home/spider/deepak_bench/apps/frappe/frappe/database/query.py", line 737, in get_query
    criterion = self.build_conditions(table, filters, **kwargs)
  File "/home/spider/deepak_bench/apps/frappe/frappe/database/query.py", line 438, in build_conditions
    criterion = self.dict_query(filters=filters, table=table, **kwargs)
  File "/home/spider/deepak_bench/apps/frappe/frappe/database/query.py", line 380, in dict_query
    _operator = self.OPERATOR_MAP["="]
  File "/usr/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/home/spider/deepak_bench/apps/frappe/frappe/database/query.py", line 241, in OPERATOR_MAP
    if frappe.get_hooks("filters_config"):
  File "/home/spider/deepak_bench/apps/frappe/frappe/__init__.py", line 1477, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", _load_app_hooks))
  File "/home/spider/deepak_bench/apps/frappe/frappe/utils/redis_wrapper.py", line 96, in get_value
    val = generator()
  File "/home/spider/deepak_bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/spider/deepak_bench/apps/frappe/frappe/__init__.py", line 1438, in _load_app_hooks
    apps = [app_name] if app_name else get_installed_apps(sort=True)
  File "/home/spider/deepak_bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/spider/deepak_bench/apps/frappe/frappe/__init__.py", line 1403, in get_installed_apps
    installed = json.loads(db.get_global("installed_apps") or "[]")
  File "/home/spider/deepak_bench/apps/frappe/frappe/database/database.py", line 879, in get_global
    return self.get_default(key, user)
  File "/home/spider/deepak_bench/apps/frappe/frappe/database/database.py", line 883, in get_default
    d = self.get_defaults(key, parent)
  File "/home/spider/deepak_bench/apps/frappe/frappe/database/database.py", line 899, in get_defaults
    defaults = frappe.defaults.get_defaults_for(parent)
  File "/home/spider/deepak_bench/apps/frappe/frappe/defaults.py", line 218, in get_defaults_for
    frappe.qb.from_(table)
  File "/home/spider/deepak_bench/apps/frappe/frappe/query_builder/utils.py", line 86, in execute_query
    return frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/spider/deepak_bench/apps/frappe/frappe/database/database.py", line 200, in sql
    self.connect()
  File "/home/spider/deepak_bench/apps/frappe/frappe/database/database.py", line 114, in connect
    self._conn = self.get_connection()
  File "/home/spider/deepak_bench/apps/frappe/frappe/database/mariadb/database.py", line 98, in get_connection
    conn = self._get_connection()
  File "/home/spider/deepak_bench/apps/frappe/frappe/database/mariadb/database.py", line 104, in _get_connection
    return self.create_connection()
  File "/home/spider/deepak_bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/spider/deepak_bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 353, in __init__
    self.connect()
  File "/home/spider/deepak_bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 664, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '127.0.0.1' ([Errno 111] Connection refused)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/spider/deepak_bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/spider/deepak_bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: -8275639797106111249

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/spider/deepak_bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 613, in connect
    sock = socket.create_connection(
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/spider/deepak_bench/apps/frappe/frappe/utils/error.py", line 47, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/spider/deepak_bench/apps/frappe/frappe/utils/error.py", line 105, in get_snapshot
    vars = cgitb.scanvars(reader, frame, locals)
  File "/usr/lib/python3.10/cgitb.py", line 88, in scanvars
    value = getattr(parent, token, __UNDEF__)
  File "/usr/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/home/spider/deepak_bench/apps/frappe/frappe/database/query.py", line 241, in OPERATOR_MAP
    if frappe.get_hooks("filters_config"):
  File "/home/spider/deepak_bench/apps/frappe/frappe/__init__.py", line 1477, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", _load_app_hooks))
  File "/home/spider/deepak_bench/apps/frappe/frappe/utils/redis_wrapper.py", line 96, in get_value
    val = generator()
  File "/home/spider/deepak_bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/spider/deepak_bench/apps/frappe/frappe/__init__.py", line 1438, in _load_app_hooks
    apps = [app_name] if app_name else get_installed_apps(sort=True)
  File "/home/spider/deepak_bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/spider/deepak_bench/apps/frappe/frappe/__init__.py", line 1403, in get_installed_apps
    installed = json.loads(db.get_global("installed_apps") or "[]")
  File "/home/spider/deepak_bench/apps/frappe/frappe/database/database.py", line 879, in get_global
    return self.get_default(key, user)
  File "/home/spider/deepak_bench/apps/frappe/frappe/database/database.py", line 883, in get_default
    d = self.get_defaults(key, parent)
  File "/home/spider/deepak_bench/apps/frappe/frappe/database/database.py", line 899, in get_defaults
    defaults = frappe.defaults.get_defaults_for(parent)
  File "/home/spider/deepak_bench/apps/frappe/frappe/defaults.py", line 218, in get_defaults_for
    frappe.qb.from_(table)
  File "/home/spider/deepak_bench/apps/frappe/frappe/query_builder/utils.py", line 86, in execute_query
    return frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/spider/deepak_bench/apps/frappe/frappe/database/database.py", line 200, in sql
    self.connect()
  File "/home/spider/deepak_bench/apps/frappe/frappe/database/database.py", line 114, in connect
    self._conn = self.get_connection()
  File "/home/spider/deepak_bench/apps/frappe/frappe/database/mariadb/database.py", line 98, in get_connection
    conn = self._get_connection()
  File "/home/spider/deepak_bench/apps/frappe/frappe/database/mariadb/database.py", line 104, in _get_connection
    return self.create_connection()
  File "/home/spider/deepak_bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/spider/deepak_bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 353, in __init__
    self.connect()
  File "/home/spider/deepak_bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 664, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '127.0.0.1' ([Errno 111] Connection refused)")
2022-11-24 11:04:54,938 ERROR frappe Could not take error snapshot: (2003, "Can't connect to MySQL server on '127.0.0.1' ([Errno 111] Connection refused)")
Site: deepak.com
Form Dict: {}
Traceback (most recent call last):
  File "/home/spider/deepak_bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/spider/deepak_bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: -8275639797106111249

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/spider/deepak_bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 613, in connect
    sock = socket.create_connection(
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/spider/deepak_bench/apps/frappe/frappe/app.py", line 42, in application
    init_request(request)
  File "/home/spider/deepak_bench/apps/frappe/frappe/app.py", line 120, in init_request
    frappe.local.http_request = HTTPRequest()
  File "/home/spider/deepak_bench/apps/frappe/frappe/auth.py", line 36, in __init__
    self.set_session()
  File "/home/spider/deepak_bench/apps/frappe/frappe/auth.py", line 70, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/spider/deepak_bench/apps/frappe/frappe/auth.py", line 115, in __init__
    self.make_session(resume=True)
  File "/home/spider/deepak_bench/apps/frappe/frappe/auth.py", line 203, in make_session
    frappe.local.session_obj = Session(
  File "/home/spider/deepak_bench/apps/frappe/frappe/sessions.py", line 238, in __init__
    self.resume()
  File "/home/spider/deepak_bench/apps/frappe/frappe/sessions.py", line 310, in resume
    validate_ip_address(self.user)
  File "/home/spider/deepak_bench/apps/frappe/frappe/auth.py", line 407, in validate_ip_address
    frappe.get_cached_value("User", user, user_fields, as_dict=True)
  File "/home/spider/deepak_bench/apps/frappe/frappe/__init__.py", line 1141, in get_cached_value
    doc = get_cached_doc(doctype, name)
  File "/home/spider/deepak_bench/apps/frappe/frappe/__init__.py", line 1082, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/spider/deepak_bench/apps/frappe/frappe/__init__.py", line 1175, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/spider/deepak_bench/apps/frappe/frappe/model/document.py", line 72, in get_doc
    controller = get_controller(doctype)
  File "/home/spider/deepak_bench/apps/frappe/frappe/model/base_document.py", line 77, in get_controller
    return _get_controller()
  File "/home/spider/deepak_bench/apps/frappe/frappe/model/base_document.py", line 47, in _get_controller
    module_name, custom = frappe.db.get_value(
  File "/home/spider/deepak_bench/apps/frappe/frappe/database/database.py", line 456, in get_value
    result = self.get_values(
  File "/home/spider/deepak_bench/apps/frappe/frappe/database/database.py", line 553, in get_values
    out = self._get_values_from_table(
  File "/home/spider/deepak_bench/apps/frappe/frappe/database/database.py", line 769, in _get_values_from_table
    query = frappe.qb.engine.get_query(
  File "/home/spider/deepak_bench/apps/frappe/frappe/database/query.py", line 737, in get_query
    criterion = self.build_conditions(table, filters, **kwargs)
  File "/home/spider/deepak_bench/apps/frappe/frappe/database/query.py", line 438, in build_conditions
    criterion = self.dict_query(filters=filters, table=table, **kwargs)
  File "/home/spider/deepak_bench/apps/frappe/frappe/database/query.py", line 380, in dict_query
    _operator = self.OPERATOR_MAP["="]
  File "/usr/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/home/spider/deepak_bench/apps/frappe/frappe/database/query.py", line 241, in OPERATOR_MAP
    if frappe.get_hooks("filters_config"):
  File "/home/spider/deepak_bench/apps/frappe/frappe/__init__.py", line 1477, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", _load_app_hooks))
  File "/home/spider/deepak_bench/apps/frappe/frappe/utils/redis_wrapper.py", line 96, in get_value
    val = generator()
  File "/home/spider/deepak_bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/spider/deepak_bench/apps/frappe/frappe/__init__.py", line 1438, in _load_app_hooks
    apps = [app_name] if app_name else get_installed_apps(sort=True)
  File "/home/spider/deepak_bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/spider/deepak_bench/apps/frappe/frappe/__init__.py", line 1403, in get_installed_apps
    installed = json.loads(db.get_global("installed_apps") or "[]")
  File "/home/spider/deepak_bench/apps/frappe/frappe/database/database.py", line 879, in get_global
    return self.get_default(key, user)
  File "/home/spider/deepak_bench/apps/frappe/frappe/database/database.py", line 883, in get_default
    d = self.get_defaults(key, parent)
  File "/home/spider/deepak_bench/apps/frappe/frappe/database/database.py", line 899, in get_defaults
    defaults = frappe.defaults.get_defaults_for(parent)
  File "/home/spider/deepak_bench/apps/frappe/frappe/defaults.py", line 218, in get_defaults_for
    frappe.qb.from_(table)
  File "/home/spider/deepak_bench/apps/frappe/frappe/query_builder/utils.py", line 86, in execute_query
    return frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/spider/deepak_bench/apps/frappe/frappe/database/database.py", line 200, in sql
    self.connect()
  File "/home/spider/deepak_bench/apps/frappe/frappe/database/database.py", line 114, in connect
    self._conn = self.get_connection()
  File "/home/spider/deepak_bench/apps/frappe/frappe/database/mariadb/database.py", line 98, in get_connection
    conn = self._get_connection()
  File "/home/spider/deepak_bench/apps/frappe/frappe/database/mariadb/database.py", line 104, in _get_connection
    return self.create_connection()
  File "/home/spider/deepak_bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/spider/deepak_bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 353, in __init__
    self.connect()
  File "/home/spider/deepak_bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 664, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '127.0.0.1' ([Errno 111] Connection refused)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/spider/deepak_bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/spider/deepak_bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: -8275639797106111249

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/spider/deepak_bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 613, in connect
    sock = socket.create_connection(
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/spider/deepak_bench/apps/frappe/frappe/utils/error.py", line 47, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/spider/deepak_bench/apps/frappe/frappe/utils/error.py", line 105, in get_snapshot
    vars = cgitb.scanvars(reader, frame, locals)
  File "/usr/lib/python3.10/cgitb.py", line 88, in scanvars
    value = getattr(parent, token, __UNDEF__)
  File "/usr/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/home/spider/deepak_bench/apps/frappe/frappe/database/query.py", line 241, in OPERATOR_MAP
    if frappe.get_hooks("filters_config"):
  File "/home/spider/deepak_bench/apps/frappe/frappe/__init__.py", line 1477, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", _load_app_hooks))
  File "/home/spider/deepak_bench/apps/frappe/frappe/utils/redis_wrapper.py", line 96, in get_value
    val = generator()
  File "/home/spider/deepak_bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/spider/deepak_bench/apps/frappe/frappe/__init__.py", line 1438, in _load_app_hooks
    apps = [app_name] if app_name else get_installed_apps(sort=True)
  File "/home/spider/deepak_bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/spider/deepak_bench/apps/frappe/frappe/__init__.py", line 1403, in get_installed_apps
    installed = json.loads(db.get_global("installed_apps") or "[]")
  File "/home/spider/deepak_bench/apps/frappe/frappe/database/database.py", line 879, in get_global
    return self.get_default(key, user)
  File "/home/spider/deepak_bench/apps/frappe/frappe/database/database.py", line 883, in get_default
    d = self.get_defaults(key, parent)
  File "/home/spider/deepak_bench/apps/frappe/frappe/database/database.py", line 899, in get_defaults
    defaults = frappe.defaults.get_defaults_for(parent)
  File "/home/spider/deepak_bench/apps/frappe/frappe/defaults.py", line 218, in get_defaults_for
    frappe.qb.from_(table)
  File "/home/spider/deepak_bench/apps/frappe/frappe/query_builder/utils.py", line 86, in execute_query
    return frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/spider/deepak_bench/apps/frappe/frappe/database/database.py", line 200, in sql
    self.connect()
  File "/home/spider/deepak_bench/apps/frappe/frappe/database/database.py", line 114, in connect
    self._conn = self.get_connection()
  File "/home/spider/deepak_bench/apps/frappe/frappe/database/mariadb/database.py", line 98, in get_connection
    conn = self._get_connection()
  File "/home/spider/deepak_bench/apps/frappe/frappe/database/mariadb/database.py", line 104, in _get_connection
    return self.create_connection()
  File "/home/spider/deepak_bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/spider/deepak_bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 353, in __init__
    self.connect()
  File "/home/spider/deepak_bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 664, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '127.0.0.1' ([Errno 111] Connection refused)")
2022-11-24 16:16:19,886 ERROR frappe New Exception collected with id: 2022-11-24 16:16:19.252867-127.0.0.1-c07
Site: deepak.com
Form Dict: {}
2022-11-24 16:20:55,613 ERROR frappe New Exception collected with id: 2022-11-24 16:20:55.302520-127.0.0.1-8d1
Site: deepak.com
Form Dict: {'doctype': 'Team Project', 'name': '14', 'cmd': 'frappe.client.get'}
2022-11-24 16:32:10,101 ERROR frappe New Exception collected with id: 2022-11-24 16:32:09.951716-127.0.0.1-fe3
Site: deepak.com
Form Dict: {'doctype': 'Team Comment', 'fields': ['name', 'content', 'owner', 'creation', 'modified', 'deleted_at'], 'filters': {'reference_doctype': 'Team Task', 'reference_name': 2}, 'order_by': 'creation asc', 'start': 0, 'limit': 99999, 'limit_start': 0, 'limit_page_length': 99999, 'debug': 0, 'cmd': 'frappe.client.get_list'}
2022-11-24 22:34:50,530 ERROR frappe New Exception collected with id: 2022-11-24 22:34:50.052764-127.0.0.1-3a9
Site: deepak.com
Form Dict: {}
